export const translations = [
    { language: 'Amharic', code: 'am', translation: 'አንብብ እና አጠቃላይ' },
    { language: 'Arabic', code: 'ar', translation: 'ملخص النص' },
    { language: 'Basque', code: 'eu', translation: 'Testu laburpena' },
    { language: 'Bengali', code: 'bn', translation: 'পাঠের সারসংক্ষেপ' },
    { language: 'English (UK)', code: 'en-GB', translation: 'Text summary' },
    { language: 'Portuguese (Brazil)', code: 'pt-BR', translation: 'Resumo do texto' },
    { language: 'Bulgarian', code: 'bg', translation: 'Резюме на текста' },
    { language: 'Catalan', code: 'ca', translation: 'Resum del text' },
    { language: 'Cherokee', code: 'chr', translation: 'ᏅᏙᎢ ᏣᎳᎩ' },
    { language: 'Croatian', code: 'hr', translation: 'Sažetak teksta' },
    { language: 'Czech', code: 'cs', translation: 'Shrnutí textu' },
    { language: 'Danish', code: 'da', translation: 'Tekstoversigt' },
    { language: 'Dutch', code: 'nl', translation: 'Tekstsamenvatting' },
    { language: 'English (US)', code: 'en', translation: 'Text summary' },
    { language: 'Estonian', code: 'et', translation: 'Teksti kokkuvõte' },
    { language: 'Filipino', code: 'fil', translation: 'Buod ng teksto' },
    { language: 'Finnish', code: 'fi', translation: 'Tekstin yhteenveto' },
    { language: 'French', code: 'fr', translation: 'Résumé du texte' },
    { language: 'German', code: 'de', translation: 'Textzusammenfassung' },
    { language: 'Greek', code: 'el', translation: 'Περίληψη κειμένου' },
    { language: 'Gujarati', code: 'gu', translation: 'પાઠનું સારાંશ' },
    { language: 'Hebrew', code: 'iw', translation: 'סיכום טקסט' },
    { language: 'Hindi', code: 'hi', translation: 'पाठ सारांश' },
    { language: 'Hungarian', code: 'hu', translation: 'Szöveges összefoglaló' },
    { language: 'Icelandic', code: 'is', translation: 'Textayfirlit' },
    { language: 'Indonesian', code: 'id', translation: 'Ringkasan teks' },
    { language: 'Italian', code: 'it', translation: 'Riassunto del testo' },
    { language: 'Japanese', code: 'ja', translation: 'テキストの要約' },
    { language: 'Kannada', code: 'kn', translation: 'ಪಠ್ಯದ ಸಾರಾಂಶ' },
    { language: 'Korean', code: 'ko', translation: '텍스트 요약' },
    { language: 'Latvian', code: 'lv', translation: 'Teksta kopsavilkums' },
    { language: 'Lithuanian', code: 'lt', translation: 'Teksto santrauka' },
    { language: 'Malay', code: 'ms', translation: 'Ringkasan teks' },
    { language: 'Malayalam', code: 'ml', translation: 'പാഠത്തിന്റെ ചുരുക്കം' },
    { language: 'Marathi', code: 'mr', translation: 'पाठ सारांश' },
    { language: 'Norwegian', code: 'no', translation: 'Tekstoppsummering' },
    { language: 'Polish', code: 'pl', translation: 'Podsumowanie tekstu' },
    { language: 'Portuguese (Portugal)', code: 'pt-PT', translation: 'Resumo do texto' },
    { language: 'Romanian', code: 'ro', translation: 'Rezumatul textului' },
    { language: 'Russian', code: 'ru', translation: 'Резюме текста' },
    { language: 'Serbian', code: 'sr', translation: 'Kratak pregled teksta' },
    { language: 'Chinese (PRC)', code: 'zh-CN', translation: '文本摘要' },
    { language: 'Slovak', code: 'sk', translation: 'Súhrn textu' },
    { language: 'Slovenian', code: 'sl', translation: 'Povzetek besedila' },
    { language: 'Spanish', code: 'es', translation: 'Resumen del texto' },
    { language: 'Swahili', code: 'sw', translation: 'Muhtasari wa maandiko' },
    { language: 'Swedish', code: 'sv', translation: 'Textsammanfattning' },
    { language: 'Tamil', code: 'ta', translation: 'உரை சுருக்கம்' },
    { language: 'Telugu', code: 'te', translation: 'పాఠం సంక్షిప్తం' },
    { language: 'Thai', code: 'th', translation: 'สรุปข้อความ' },
    { language: 'Chinese (Taiwan)', code: 'zh-TW', translation: '文本摘要' },
    { language: 'Turkish', code: 'tr', translation: 'Metin özeti' },
    { language: 'Urdu', code: 'ur', translation: 'متن کا خلاصہ' },
    { language: 'Ukrainian', code: 'uk', translation: 'Резюме тексту' },
    { language: 'Vietnamese', code: 'vi', translation: 'Tóm tắt văn bản' },
    { language: 'Welsh', code: 'cy', translation: 'Crynodeb testun' }
];